metadatabase_file: /common/tmp/sjackson/level2.stfc.db
readers:
  uda:
    type: 'uda'
  fairmast:
    type: 'zarr'
    options:
      base_path: 's3://mast/level1/shots'
      protocol: 'simplecache'
      target_protocol: "s3"
      target_options:
          anon: True 
          endpoint_url: "https://s3.echo.stfc.ac.uk"

writer:
  type: "netcdf"
  options:
    zarr_format: 2
    output_path: "/common/tmp/sjackson/rtdi"

# upload:
#   base_path: "s3://fairmast/mastu/level2/shots"
#   mode: 's5cmd'
#   credentials_file: "../fair-mast-ingestion/.s5cfg.ukaea"
#   endpoint_url: "http://mon3.cepheus.hpc.l:8000"

