name: CI
on: [ push ]

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up environment
      run: |
        git lfs fetch
        git lfs pull
        pip install uv
        sudo apt install libopenmpi-dev
        uv venv venv
        source venv/bin/activate
        uv pip install -r requirements.txt
  
    - name: Run tests
      run: |
        source venv/bin/activate
        python -m pytest -rsx tests/

  ruff-code-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: chartboost/ruff-action@v1  